// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ru'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	home: {
		/**
		 * Д​м​и​т​р​и​й​ ​С​к​р​ы​л​ь​н​и​к​о​в
		 */
		userName: string
	}
	preview: {
		/**
		 * Ч​и​т​а​т​ь​ ​д​а​л​е​е
		 */
		readMore: string
	}
	post: {
		/**
		 * Р​е​д​а​к​т​и​р​о​в​а​т​ь
		 */
		edit: string
	}
	/**
	 * E​n​g​l​i​s​h
	 */
	changeLang: string
}

export type TranslationFunctions = {
	home: {
		/**
		 * Дмитрий Скрыльников
		 */
		userName: () => LocalizedString
	}
	preview: {
		/**
		 * Читать далее
		 */
		readMore: () => LocalizedString
	}
	post: {
		/**
		 * Редактировать
		 */
		edit: () => LocalizedString
	}
	/**
	 * English
	 */
	changeLang: () => LocalizedString
}

export type Formatters = {}
