# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Copy code
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: ${{ secrets.SOURCE }}
          TARGET: ${{ secrets.TARGET }}
          ARGS: "-rlgozvc -i"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          sync: true
          script: cd /root/prod/dskr.dev && pnpm i && pnpm build && pm2 start ecosystem.config.js --env production --only dskr-dev
